### ISSUE TITLE
HITSOUND ERRORS!

### ISSUE THREAD

**Issue by yesSIRgithubtings** [TheRatCode/RatPoison#333]
java.lang.NullPointerException
        at rat.poison.scripts.esp.HitsoundESPKt.updateHitsound(HitsoundESP.kt:43)
        at rat.poison.scripts.esp.HitsoundESPKt$hitSoundEsp$$inlined$every$1.run(Every.kt:27)
        at java.lang.Thread.run(Unknown Source)

**Comment by Overman999** [comment]
I've got the same error

**Comment by retart1337** [comment]
Probably you was trying to use hitsounds with MENU= false
that was fixed in newesr versions
