### ISSUE TITLE
Exception upon running Start Ratpoison.bat

### ISSUE THREAD

**Issue by rdcrGithub** [TheRatCode/RatPoison#338]
hi, I was able to build the source but when I attempt to run it I get an exception.

Exception in thread "main" java.lang.NoSuchMethodError: getFontPeer
        at java.awt.Font.initIDs(Native Method)
        at java.awt.Font.<clinit>(Unknown Source)
        at sun.awt.windows.WComponentPeer.<clinit>(Unknown Source)
        at java.awt.Component.initIDs(Native Method)
        at java.awt.Component.<clinit>(Unknown Source)
        at sun.awt.windows.WToolkit.initIDs(Native Method)
        at sun.awt.windows.WToolkit.<clinit>(Unknown Source)
        at sun.awt.Win32GraphicsEnvironment.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at java.awt.GraphicsEnvironment.createGE(Unknown Source)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(Unknown Sour
ce)
        at java.awt.Robot.<init>(Unknown Source)
        at rat.poison.RatPoison.<clinit>(RatPoison.kt:79)

CSGO is open.
Version is 1.6.

**Comment by matt1tk** [comment]
Does this happen every time you run it? try running it again a few times

**Comment by rdcrGithub** [comment]
I was never able to run it successfully after building.

**Comment by matt1tk** [comment]
Have you rebuilt yet? Try that.

**Comment by rdcrGithub** [comment]
I have rebuilt, yes.
