### ISSUE TITLE
Flat Aim not working

### ISSUE THREAD

**Issue by phooooon** [TheRatCode/RatPoison#368]
title. flat aim is just flat out not working. it also spams setaim faliure in the console

**Comment by phooooon** [comment]
java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:549)
        at rat.poison.scripts.aim.FlatAimKt$flatAim$$inlined$aimScript$1.run(Every.kt:103)
        at java.base/java.lang.Thread.run(Thread.java:835)
SetAim failure
