### ISSUE TITLE
Issue with downloading JDK.

### ISSUE THREAD

**Issue by tymurg** [TheRatCode/RatPoison#374]
when i click on the links to install the jdk 13, i click on both the windows installation things and it says error, anyways i launch the build thing, click yes or no, i tried both and when i thought jdk was installed, it said dis on both yes or no when i launched.

Could not unzip C:\Users\tymur\.gradle\wrapper\dists\gradle-4.10.3-all\81msde2dx9p4vji0mjgtvxkcb\gradle-4.10.3-all.zip to C:\Users\tymur\.gradle\wrapper\dists\gradle-4.10.3-all\81msde2dx9p4vji0mjgtvxkcb.
Reason: zip END header not found
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1371)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:183)
        at org.gradle.wrapper.Install.unzip(Install.java:218)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

help please? sorry if its confusing i don't even kno what im doing

**Comment by tymurg** [comment]
Also i forgot to mention, when i install the JDk or try, i cant tell if its installed because its no where in file explorer. Does this indicate its not installed? ty

**Comment by matt1tk** [comment]
http://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.msi 

Download and run this, then type N in the build.bat.
