### ISSUE TITLE
"F1 Menu" issues

### ISSUE THREAD

**Issue by h04X-2K** [TheRatCode/RatPoison#385]
if i put menu from false to true then i get this error

Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
Exception in thread "DefaultDispatcher-worker-1" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.lang.ExceptionInInitializerError
        at rat.poison.ui.UIMenu.<init>(UIMenu.kt:45)
        at rat.poison.App.create(RatPoison.kt:233)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        ... 6 more
Caused by: java.lang.IllegalStateException: ColorPicker shader compilation failed. Shader: default.vert, palette.frag: Vertex shader
Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

Fragment shader:
Fragment shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

        at com.kotcrab.vis.ui.widget.color.internal.PickerCommons.loadShader(PickerCommons.java:79)
        at com.kotcrab.vis.ui.widget.color.internal.PickerCommons.loadShaders(PickerCommons.java:63)
        at com.kotcrab.vis.ui.widget.color.internal.PickerCommons.<init>(PickerCommons.java:50)
        at com.kotcrab.vis.ui.widget.color.BasicColorPicker.<init>(BasicColorPicker.java:122)
        at com.kotcrab.vis.ui.widget.color.ExtendedColorPicker.<init>(ExtendedColorPicker.java:68)
        at com.kotcrab.vis.ui.widget.color.ColorPicker.<init>(ColorPicker.java:86)
        at com.kotcrab.vis.ui.widget.color.ColorPicker.<init>(ColorPicker.java:65)
        at rat.poison.ui.uiHelpers.VisColorPickerCustom.<init>(VisColorPickerCustom.kt:25)
        at rat.poison.ui.tabs.VisualsTab.<init>(VisualsTab.kt:40)
        at rat.poison.ui.UIMenuKt.<clinit>(UIMenu.kt:14)
        ... 12 more

**Comment by h04X-2K** [comment]
@TheFuckingRat if found this 
//The title of the app to draw the overlay on
//Ex "Untitled - Notepad"

means that he is using notepad if yes the problem is with me because I don't have notepad anymore but only notepad++

**Comment by M1XT3NZ** [comment]
Notepad can’t be uninstalled (afaik) because it’s a standard windows
application,
The notepad++ exe is just notepad++.exe
