### ISSUE TITLE
Crashing overlay Bounds exceeds available space

### ISSUE THREAD

**Issue by GeRikz** [TheRatCode/RatPoison#509]
java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=45932, offset=45948
        at com.sun.jna.Memory.boundsCheck(Memory.java:220)
        at com.sun.jna.Memory.getInt(Memory.java:484)
        at rat.poison.game.entity.PlayerKt.armor(Player.kt:64)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:110)
        at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
        at rat.poison.App.render(RatPoison.kt:339)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:153)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by sotakoira** [comment]
outdated version, been fixed for a month or so

**Comment by GeRikz** [comment]
> outdated version, been fixed for a month or so

re-downloaded made build and still same issue if not enabling box esp works fine

**Comment by sotakoira** [comment]
it is this https://github.com/TheFuckingRat/RatPoison/blob/master/src/main/kotlin/rat/poison/scripts/esp/BoxESP.kt#L65
seems to not be fixed in 1.6, in 1.7 beta it has been fixed since 13th june

**Comment by GeRikz** [comment]
> it is this https://github.com/TheFuckingRat/RatPoison/blob/master/src/main/kotlin/rat/poison/scripts/esp/BoxESP.kt#L65
> seems to not be fixed in 1.6, in 1.7 beta it has been fixed since 13th june

how i can build 1.7 beta version ?

**Comment by sotakoira** [comment]
change branch from master to beta, rest is the same
