### ISSUE TITLE
Was working fine till today

### ISSUE THREAD

**Issue by r0ot7** [TheRatCode/RatPoison#511]
Throwing null pointer exception (v 1.7):

```
SetAim failure
SetAim failure
kotlin.KotlinNullPointerException
        at rat.poison.game.netvars.NetVar.getValue(NetVar.kt:13)
        at rat.poison.game.netvars.NetVarOffsets.getVecOrigin(NetVarOffsets.kt)
        at rat.poison.game.entity.EntityKt.absPosition(Entity.kt:63)
        at rat.poison.game.hooks.EntityIterationKt$constructEntities$$inlined$every$1.run(Every.kt:41)
SetAim failure
        at java.base/java.lang.Thread.run(Thread.java:830)
```

For v1.6

```
`Initializing overlay
Exception in thread "DefaultDispatcher-worker-1" kotlin.KotlinNullPointerException
        at rat.poison.game.netvars.NetVar.getValue(NetVar.kt:13)
        at rat.poison.game.netvars.NetVarOffsets.getM_iDefaultFov(NetVarOffsets.kt)
        at rat.poison.scripts.RCrosshairKt$rcrosshair$1.invoke(RCrosshair.kt:43)
        at rat.poison.scripts.RCrosshairKt$rcrosshair$1.invoke(RCrosshair.kt)
        at rat.poison.App.render(RatPoison.kt:339)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)`
```

**Comment by r0ot7** [comment]
For v1.6

`Initializing overlay
Exception in thread "DefaultDispatcher-worker-1" kotlin.KotlinNullPointerException
        at rat.poison.game.netvars.NetVar.getValue(NetVar.kt:13)
        at rat.poison.game.netvars.NetVarOffsets.getM_iDefaultFov(NetVarOffsets.kt)
        at rat.poison.scripts.RCrosshairKt$rcrosshair$1.invoke(RCrosshair.kt:43)
        at rat.poison.scripts.RCrosshairKt$rcrosshair$1.invoke(RCrosshair.kt)
        at rat.poison.App.render(RatPoison.kt:339)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)`
