### ISSUE TITLE
Build [BUG]

### ISSUE THREAD

**Issue by 1oddynuff** [TheRatCode/RatPoison#675]
When i try to build the newest version i get this message. I've had 1.6 previously if that matters

Building RatPoison...
Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
        at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:111)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: No build receipt resource found.
        at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:97)
        ... 1 more
Build failed. Would you like to have installer download JDK for you and try again? [Y/N]

**Comment by SPRAVEDLIVO** [comment]
https://github.com/TheRatCode/RatPoison/releases

**Comment by SPRAVEDLIVO** [comment]
https://github.com/TheRatCode/RatPoison/actions/runs/417501280
