### ISSUE TITLE
[BUG]Load config crash cheat

### ISSUE THREAD

**Issue by TreeV2** [TheRatCode/RatPoison#676]
When i inject the cheat and load my config the cheat crash and in console is this code : 

Loading settings... settings\CFGS\trying to make zuhn cfg.cfg
Settings loaded
FATAL ERROR in native method: Thread[DefaultDispatcher-worker-2,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
        at org.lwjgl.opengl.GL11C.nglGenTextures(Native Method)
        at org.lwjgl.opengl.GL11C.glGenTextures(GL11C.java:664)
        at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:2492)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3GL20.glGenTexture(Lwjgl3GL20.java:348)
        at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
        at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page$1.<init>(PixmapPacker.java:504)
        at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page.updateTexture(PixmapPacker.java:504)
        at com.badlogic.gdx.graphics.g2d.PixmapPacker.updatePageTextures(PixmapPacker.java:410)
        - locked <0x00000000e00fa1c8> (a com.badlogic.gdx.graphics.g2d.PixmapPacker)
        at com.badlogic.gdx.graphics.g2d.PixmapPacker.updateTextureRegions(PixmapPacker.java:402)
        - locked <0x00000000e00fa1c8> (a com.badlogic.gdx.graphics.g2d.PixmapPacker)
        at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:464)
        at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:161)
        at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:152)
        at rat.poison.utils.AssetManager.updateFonts(AssetManager.kt:78)
        at rat.poison.ui.tabs.FontsTab$2.invoke(FontsTab.kt:52)
        at rat.poison.ui.tabs.FontsTab$2.invoke(FontsTab.kt:20)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:158)
        at com.badlogic.gdx.scenes.scene2d.ui.ProgressBar.setValue(ProgressBar.java:303)
        at rat.poison.ui.uiHelpers.VisSliderCustom.update(VisSliderCustom.kt:54)
        at rat.poison.ui.tabs.FontsTabKt.fontsTabUpdate(FontsTab.kt:111)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:45)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:29)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:14)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox.update(ATabVisCheckBox.kt:41)
        at rat.poison.ui.tabs.AimTabKt.updateAim(AimTab.kt:171)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:43)
        at rat.poison.ui.tabs.aimtabs.OverrideTab$7.invoke(OverrideTab.kt:241)
        at rat.poison.ui.tabs.aimtabs.OverrideTab$7.invoke(OverrideTab.kt:23)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.tabs.AimTabKt.updateAim(AimTab.kt:141)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:43)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:29)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:14)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox.update(ATabVisCheckBox.kt:41)
        at rat.poison.ui.tabs.AimTabKt.updateTrig(AimTab.kt:291)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:42)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:29)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:14)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox.update(ATabVisCheckBox.kt:41)
        at rat.poison.ui.tabs.AimTabKt.updateTrig(AimTab.kt:290)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:42)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:29)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:14)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox.update(ATabVisCheckBox.kt:41)
        at rat.poison.ui.tabs.AimTabKt.updateTrig(AimTab.kt:288)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:42)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:29)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:14)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox.update(ATabVisCheckBox.kt:41)
        at rat.poison.ui.tabs.AimTabKt.updateTrig(AimTab.kt:287)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:42)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:29)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:14)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox.update(ATabVisCheckBox.kt:41)
        at rat.poison.ui.tabs.AimTabKt.updateTrig(AimTab.kt:286)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:42)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:29)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox$1.invoke(ATabVisCheckBox.kt:14)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.uiHelpers.aimTab.ATabVisCheckBox.update(ATabVisCheckBox.kt:41)
        at rat.poison.ui.tabs.AimTabKt.updateBacktrack(AimTab.kt:344)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:40)
        at rat.poison.ui.tabs.aimtabs.OverrideTab$3.invoke(OverrideTab.kt:170)
        at rat.poison.ui.tabs.aimtabs.OverrideTab$3.invoke(OverrideTab.kt:23)
        at rat.poison.ui.UIUtilKt$changed$listener$1.changed(UIUtil.kt:11)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:115)
        at rat.poison.ui.tabs.aimtabs.OverrideTabKt.overridenWeaponsUpdate(OverrideTab.kt:298)
        at rat.poison.ui.UIUpdateKt.uiUpdate(UIUpdate.kt:21)
        at rat.poison.utils.ConfigToolsKt$loadCFG$1.invokeSuspend(ConfigTools.kt:83)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
AL lib: (EE) alc_cleanup: 1 device not closed

Some help ?

**Comment by SPRAVEDLIVO** [comment]
version?

**Comment by TreeV2** [comment]
1.8.4

**Comment by TreeV2** [comment]
[Mycfg.zip](https://github.com/TheRatCode/RatPoison/files/5698256/Mycfg.zip)
This is my cfg

**Comment by SPRAVEDLIVO** [comment]
Reproduced. Got the same error.

**Comment by SPRAVEDLIVO** [comment]
How to fix: set FONT_SIZE to 15, instead of 17.

**Comment by TreeV2** [comment]
Yeah it fix my error

**Comment by SPRAVEDLIVO** [comment]
Can't figure whats the issue atm, not closing for now
