### ISSUE TITLE
[BUG] ESP and Nade Helper Crash

### ISSUE THREAD

**Issue by Asviix** [TheRatCode/RatPoison#691]
**Describe the bug**
Crash when using Nade Helper and Box ESP

**To Reproduce**
Just use Nade Helper along with Box ESP

**Pictures/Videos**
```
Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalStateException: Call end() before beginning a new shape batch.
        at com.badlogic.gdx.graphics.glutils.ShapeRenderer.begin(ShapeRenderer.java:206)
        at com.badlogic.gdx.graphics.glutils.ShapeRenderer.begin(ShapeRenderer.java:199)
        at rat.poison.scripts.NadeHelperKt$nadeHelper$1.invoke(NadeHelper.kt:82)
        at rat.poison.scripts.NadeHelperKt$nadeHelper$1.invoke(NadeHelper.kt)
        at rat.poison.overlay.App.render(App.kt:188)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:177)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Press any key to continue . . .
```

**Comment by SPRAVEDLIVO** [comment]
version?

**Comment by Asviix** [comment]
Right after this commit #669

**Comment by SPRAVEDLIVO** [comment]
redownload when alpha will be merged into beta, never got this error and cba to reproduce
