### ISSUE TITLE
Entity errors

### ISSUE THREAD

**Issue by firenight123** [TheRatCode/RatPoison#741]
forEntities error, report in discord
[Lrat.poison.game.entity.EntityType;@66e986f9
java.lang.NullPointerException
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:144)
        at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:504)
        at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:479)
        at com.badlogic.gdx.graphics.g2d.BitmapFont.draw(BitmapFont.java:204)
        at rat.poison.scripts.visuals.BoxESPKt$boxEsp$2.invoke(BoxESP.kt:404)
        at rat.poison.scripts.visuals.BoxESPKt$boxEsp$2.invoke(BoxESP.kt)
        at rat.poison.overlay.App.render(App.kt:174)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:169)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by thefuckingrap** [comment]
breh
