### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by pigeon-cn-0** [TheRatCode/RatPoison#751]
java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at rat.poison.scripts.visuals.GlowESPKt$glowEspEvery$$inlined$every$1.run(Every.kt:83)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at rat.poison.scripts.BacktrackKt.constructRecords(Backtrack.kt:353)
        at rat.poison.scripts.BacktrackKt$setupBacktrack$$inlined$every$1.run(Every.kt:29)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at rat.poison.scripts.visuals.FootStepESPKt$constructSteps$$inlined$every$1.run(Every.kt:48)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by SPRAVEDLIVO** [comment]
what version are you using

**Comment by pigeon-cn-0** [comment]
> 您正在使用什么版本

RatPoison-1.8.5.5

**Comment by pigeon-cn-0** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by SPRAVEDLIVO** [comment]
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

doesn't matter for anything
this shows up because of ktor dependency

**Comment by pigeon-cn-0** [comment]
Exception in thread "DefaultDispatcher-worker-2" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at rat.poison.scripts.visuals.NadesTimerKt$nadesTimer$1.invoke(NadesTimer.kt:62)
        at rat.poison.scripts.visuals.NadesTimerKt$nadesTimer$1.invoke(NadesTimer.kt)
        at rat.poison.overlay.App.render(App.kt:185)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:188)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

The game quit, only this one is left

**Comment by thefuckingrap** [comment]
idk

**Comment by thefuckingrap** [comment]
The south will rise again
