### ISSUE TITLE
Failed to Install 

### ISSUE THREAD

**Issue by thekais3r** [TheRatCode/RatPoison#752]
Building RatPoison...
Could not unzip C:\Users\-\.gradle\wrapper\dists\gradle-4.10.3-all\81msde2dx9p4vji0mjgtvxkcb\gradle-4.10.3-all.zip to C:\Users\-\.gradle\wrapper\dists\gradle-4.10.3-all\81msde2dx9p4vji0mjgtvxkcb.
Reason: zip END header not found
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1502)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1397)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1404)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:237)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:167)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
        at org.gradle.wrapper.Install.unzip(Install.java:218)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Build failed. Would you like to have installer download JDK for you and try again? [Y/N]

and when picked no, same problem occurs

**Comment by SPRAVEDLIVO** [comment]
use released

**Comment by persvensoon** [comment]
Make sure you set the correct path to JDK in the windows environment and try the latest version 1.8.5.5

**Comment by 9191929992** [comment]
Stfu

**Comment by thefuckingrap** [comment]
that sucks
